name: Daily DB Update

on:
  schedule:
    
    - cron: "00 3 * * 1-5"   # seg–sex 06:30 UTC
  workflow_dispatch: {}       # permite rodar manualmente pelo GitHub

concurrency:
  group: update-database
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater (with retries)
        env:
          NEONBASE_URL: ${{ secrets.NEONBASE_URL }}
        run: |
          set -euxo pipefail
          python - <<'PY'
          import time, subprocess, sys
          for i in range(3):
              try:
                  subprocess.check_call([sys.executable, "-m", "update_all.py"])
                  sys.exit(0)
              except subprocess.CalledProcessError:
                  if i==2: raise
                  time.sleep(30)
          PY
